language: node_js
node_js:
- 6
- 8
- 9
script:
- npm run lint
- npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
